dicionario_marcadores = {
	'conclusões':[r'^Acolhe.{1,5}se.*?[\.\:]', 
	r'^(Ante|Por todo|Pelo|Diante).{1,30}exposto.*?[\.\:]', 
	r'^Assim.*?[\.\:]', 
	r'^Dado.{1,20}que.*?[\.\:]', 
	r'^Em conclusão.*?[\.\:]', 
	r'^Em suma.*?[\.\:]', 
	r'^Finalmente.*?[\.\:]', 
	r'^No mais.*?[\.\:]', 
	r'^Por fim.*?[\.\:]',
	r'^Por ser deste modo.*?[\.\:]',
	r'^Rejeitam-se.*?[\.\:]'
	],
	'continuidade do argumento' : [r'^Ademais.*?[\.\:]', 
	r'^Ainda.*?[\.\:]', 
	r'^Além disso.*?[\.\:]', 
	r'^Com efeito.*?[\.\:]',
	r'^Contudo.*?[\.\:]',
	r'^De igual modo.*?[\.\:]', 
	r'^De outra parte.*?[\.\:]', 
	r'^De qualquer forma.*?[\.\:]',
	r'^Des.e modo.*?[\.\:]', 
	r'^Destarte.*?[\.\:]', 
	r'^Em suma.*?[\.\:]',
	r'^Igualmente.*?[\.\:]', 
	r'^Logo.*?[\.\:]', 
	r'^Na esteira desse entendimento.*?[\.\:]',
	r'^Nesse sentido,.*?[\.\:]',
	r'^No caso dos autos.*?[\.\:]', 
	r'^Ora.*?[\.\:]', 
	r'^Outrossim.*?[\.\:]', 
	r'^Porém.*?[\.\:]',
	r'^Portanto.*?[\.\:]', 
	r'^Registre\-se.*?[\.\:]', 
	r'^Também.*?[\.\:]', 
	r'^Todavia.*?[\.\:]'
	],
	'dispositivo':r'\n\s+.{1,20}dispositivo|\n\s+DISPOSITIVO|ACORDAM\n\s+',
	'fundamentação':r'\n\s+É O RELATÓRIO|\n\s+FUNDAMENTAÇÃO|\n\s+É o relatório',
	'fundamentação_dispositivo':r'\n\s+.{1,20}dispositivo|\n\s+DISPOSITIVO|\n\s+ACORDAM|\n\s+É O RELATÓRIO|\n\s+FUNDAMENTAÇÃO|\n\s+É o relatório',
	'indicação de tópico' : [r'^Quanto [àao].*?[\.\:],', 
	r'^Alega .*?[\.\:]',
	r'^Antes de mais nada.*?[\.\:]', 
	r'^Com.{1,30}vênia.*?[\.\:]', 
	r'^Conforme verificado.*?[\.\:]', 
	r'^No que (tange|se refere|diz respeito|toca).*?[\.\:]', 
	r'^No sentido d.*?[\.\:]', 
	r'^(Ocorre|Consta) que.*?[\.\:]', 
	r'^Trata-se de.*?[\.\:]',
	r'^Vale (salientar|ressaltar).*?[\.\:]',
	r'^Consta que.*?[\.\:]'
	],
	'início de parágrafo' : r'\n\s+'
}