palavras_interesse = {
    'procedente':'decisao',
    'procedencia':'decisao',
    'dar.{,10}provimento':'decisao',
    'provido':'decisao',
    'acolhimento':'decisao',
    'sumula':'lei',
    'art ':'lei',
    'conden':'decisao',
    'absolv':'decisao',
    'acordam':'decisao',
    'esclarece':'fato',
    'interpo':'pedido',
    'assere':'pedido',
    'pede':'pedido',
    'solicita ':'pedido',
    'seja condenado':'pedido',
    'seja deferido':'pedido',
    'lei':'lei',
    'determino':'decisao',
    'pretende':'pedido',
    'provimento':'decisao',
    'trata-se':'fato',
    'pleitea':'pedido',
    'conced':'decisao',
    'laudo':'fato',
    'prova':'fato',
    'pericia':'fato',
    'artigo':'lei',
    'pedido':'pedido',
    'afirma':'fato',
    'argumenta':'fato',
    'sustenta':'fato',
    'aduz':'fato',
    'deduz':'fato',
    'código':'lei',
    'extingo':'decisao',
    'extinguir':'decisao',
    'assever':'fato',
    'constata-se':'fato',
    'celeb.{1,30}acordo':'decisao',
    'homolog.{1,30}acordo':'decisao',
    'cite':'decisao',
    'intime':'decisao',
    'no caso':'fato',
    'expeça':'decisao',
    'arquive':'decisao',
    'emende':'decisao'
}
