
re_final_am = r'(\nPROCESSO DIGITAL: |\nDe ordem d[oa]|\nDespacho proferido pel|\n\d+ - Apelação n|\nProcesso n\. (?=\d{7})|\nProcesso :(?=\d{7})|\n\d+\. PROCESSO:(?=\d{7})|\nAutos n(?=\s*?\d{7})|\n\s*?ADV:)'
re_final_ac = r'(Acórdão n|\n\d+\. Classe|\n\d+ - (?=\d{7})|\nADV:|\nProcesso: |\nProcesso (?=\d+)|\nAutos n\.º|IV - ADMINISTRATIVO)'
re_final_ce = r'(\n.*?DESPACHO DE RELATORES|\n.*?DEC\s*?ISÃO MONOCRÁT\s?ICA|\n.*?EMENTA E CONCLUSÃO|\n.*?PORTAR\s*?IA|\n.*?CONFL\s*?ITO DE JUR\s*?ISD|\n.*?EMBARGOS DE DECLARAÇÃO|\n.*?APELAÇÃO|\nD\s*?ISTR\s*?IBU\s*?IÇÃO|\n[Nn]º (?=\d\d\d\d+))'
re_final_ma = r'(\nREQUERIMENTO DE |\nPETIÇÃO N|\nHABEAS CORPUS N|\nPORTARIA-TJ|\n\d{1,3}-PROCESSO|\nACÓRDÃO N|\nProcesso [Nn]º|\nProcesso:)'
re_final_pb = r'(\nAPELAÇÃO|\nEMBARGOS DE|\nAGRAVO|\nCONFLITO NEGATIVO|\nMANDADO DE SEGUR|\nRECURSO EM SENTIDO|\nREEXAME|\nRELATOR\(A\):|\nCOMARCA D|\nProcesso:|\nAgravo de Instrumento)'
re_final_pi = r'(\nPROCESSOS N|\n\d{1,3}\.\d{1,3}\. HABEAS CORPUS|\n\d{1,3}\.\d{1,3}\. AGRAVO DE INSTRUMENTO N|\n\d{1,3}\.\d{1,3}\. REEXAME NECESSÁRIO N|\n\d{1,3}\.\d{1,3}\. APELAÇÃO|\n\d{1,3}\.\d{1,3}\. MANDADO DE SEGURANÇA|\n\d{1,3}\.\d{1,3}\. DESPACHO|\n\d{1,3}\.\d{1,3}\. EDITAL |\n\d{1,3}\.\d{1,3}\. AVISO|\n\d{1,3}\.\d{1,3}\. ATO ORDINATÓRIO|\n\d{1,3}\.\d{1,3}\. SENTENÇA|\n\d{1,3}\.\d{1,3}\. AC.RDÃO)'
re_final_rn = r'(\nAPELAÇÃO|\nEMBARGOS DE|\nAGRAVO|\nCONFLITO NEGATIVO|\nMANDADO DE SEGUR|\nEXECUÇÃO N|\nEmbargos de|\nAgravo Interno|\nMandado de Segurança|\nApelação|\nExecução|\nAção Rescisória|\nADV:|\nAgravo de Instrumento)'
re_final_ro = r'(\nOrigem:|\nMandado de Segurança|\nNúmero do Processo|\nProcesso n|\nProc\.:|\nProcesso:)'
re_final_sc = r'(\n\s*ADV:|\nProcesso\s*(?=\d{7})|\n\d*\s*\.*\s*?Recurso |\n\d*\s*\.*\s*?Ag\s*ra\s*vo |\n\d*\s*\.*\s*?Embargo|\n\d*\s*\.*\s*?Apelação |\nRecurso |\n\s*N.\s*:(?=\d{4,7}))'
re_final_stf = r'(\nHABEAS CORPUS\s*?(?=\d+)|\nAGRAVO DE INSTRUMENTO\s*?(?=\d+)|\nMANDADO DE SEGURANÇA\s*?(?=\d+)|\nRECLAMAÇÃO\s*?(?=\d.\d+)|\nRECURSO EXTRAORDINÁRIO COM AGRAVO (?=\d+)|\nRECURSO EXTRAORDINÁRIO (?=\d+)|\nAG\.REG\.|\nEMB\.DECL\. (?=\d+)|\nAÇÃO DIRETA DE INCONSTITUCIONALIDADE (?=\d+)|\nAÇÃO ORIGINÁRIA (?=\d+)|\nAÇÃO PENAL (?=\d+)|\nMEDIDA CAUTELAR NA RECLAMAÇÃO (?=\d+)|\nMEDIDA CAUTELAR NA RECLAMAÇÃO (?=\d+)|\nCUMPRIMENTO DE SENTENÇA NA AÇÃO (?=\d+)|\nEXECUÇÃO CONTRA A FAZENDA (?=\d+)|\nEXTRADIÇÃO (?=\d+)|\nRECURSO ORDINÁRIO (?=\d+)|\nSEGUNDO AG\.REG\. (?=\d+))'
re_final_stj = r'(\nMANDADO DE SEGURANÇA [Nn]º|\nRECURSO ESPECIAL [Nn]º|\nAGRAVO EM RECURSO ESPECIAL [Nn]º|\nAgInt no RECURSO ESPECIAL [Nn]º|\nAgInt no RCD na MEDIDA CAUTELAR [Nn]º|\nEDcl no AgRg no RECURSO ESPECIAL [Nn]º|\nAgRg no AGRAVO EM RECURSO ESPECIAL [Nn]º|\nAgRg no RECURSO ESPECIAL [Nn]º|\nRECURSO EM HABEAS CORPUS [Nn]º|\nHABEAS CORPUS [Nn]º)'
re_final_to = r'(\nAutos|\nAUTOS N|\nProcesso N|\n\d+- Ação:|\nAÇÃO|\nEDITAL DE CITAÇÃO|\nEDITAL DE INTIMAÇÃO|\nPROCESSO N)'
re_final_trf4 = r'(\nAPELAÇÃO CÍVEL Nº|\nAPELAÇÃO.*?REMESSA NECESSÁRIA Nº|\nAGRAVO DE INSTRUMENTO Nº|\nEMBARGOS DE DECLARAÇÃO |\nEXECUÇÃO FISCAL Nº|\nPROCEDIMENTO COMUM Nº|\nEXECUÇÃO DE SENTENÇA CONTRA FAZENDA |\nEXECUÇÃO DE TÍTULO |\nEXECUÇÃO H\s*?IPOTECÁ|\nAÇÃO PENAL Nº|\nMON\s*?ITÓR\s*?IA Nº|\nREMESSA NECESSÁRIA CÍVEL Nº|\nAPELAÇÃO.*?REEXAME NECESSÁRIO Nº)'
re_num_cnj = r'\d{7}\s*-\s*\d{2}\s*\.\s*\d{4}\s*\.\s*\d{1}\s*\.\s*\d{2}\s*\.\s*\d{4}'
re_num_stf_stj = r'\d.*?( -)'
re_num_trf_trt =r'\d{7}\s*?-\d{2}\s*?\.\d{4}\s*?\.\d{1}\s*?\.\d{2}\s*?\.\d{4}|\d{7}\s*?-\d{2}\s*?\.\d{4}\s*?\.\d{3}\s*?\.\d{4}|\d{15}'

diarios = [
			['sp',
			r'\n\s*Processo\s*(?=\d{7})(.*?)(\n\s*Processo|\n\s*?N.\s*(?=\d{7}|\n(?=.*)Processo D\s*ig\s*i\s*ta\s*l))',
			r'\n\s*?N.\s*(?=\d{7})(.*?)(\n\s*Processo|\n\s*?N.\s*(?=\d{7}|\n(?=.*)Processo D\s*ig\s*i\s*ta\s*l))',
			r'\n(?=.*)Processo D\s*ig\s*i\s*ta\s*l(.*?)(\n\s*Processo|\n\s*?N.\s*(?=\d{7}|\n(?=.*)Processo D\s*ig\s*i\s*ta\s*l))'
			],
			['stf',
			r'\nHABEAS CORPUS\s*?(?=\d+)(.*?){}'.format(re_final_stf),
			r'\nAGRAVO DE INSTRUMENTO\s*?(?=\d+)(.*?){}'.format(re_final_stf),
			r'\nMANDADO DE SEGURANÇA\s*?(?=\d+)(.*?){}'.format(re_final_stf),
			r'\nRECLAMAÇÃO\s*?(?=\d.\d+)(.*?){}'.format(re_final_stf),
		  	r'\nRECURSO EXTRAORDINÁRIO COM AGRAVO (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nRECURSO EXTRAORDINÁRIO (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nAG\.REG\.(.*?){}'.format(re_final_stf),
			r'\nEMB\.DECL\. (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nAÇÃO DIRETA DE INCONSTITUCIONALIDADE (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nAÇÃO ORIGINÁRIA (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nAÇÃO PENAL (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nMEDIDA CAUTELAR NA RECLAMAÇÃO (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nCUMPRIMENTO DE SENTENÇA NA AÇÃO (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nEXECUÇÃO CONTRA A FAZENDA (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nEXTRADIÇÃO (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nRECURSO ORDINÁRIO (?=\d+)(.*?){}'.format(re_final_stf),
			r'\nSEGUNDO AG\.REG\. (?=\d+)(.*?){}'.format(re_final_stf)
			],
			['stj',
			r'\nMANDADO DE SEGURANÇA [Nn]º(.*?){}'.format(re_final_stj),
			r'\nRECURSO ESPECIAL [Nn]º(.*?){}'.format(re_final_stj),
			r'\nAGRAVO EM RECURSO ESPECIAL [Nn]º(.*?){}'.format(re_final_stj),
			r'\nAgInt no RECURSO ESPECIAL [Nn]º(.*?){}'.format(re_final_stj),
			r'\nAgInt no RCD na MEDIDA CAUTELAR [Nn]º(.*?){}'.format(re_final_stj),
			r'\nEDcl no AgRg no RECURSO ESPECIAL [Nn]º(.*?){}'.format(re_final_stj),
			r'\nAgRg no AGRAVO EM RECURSO ESPECIAL [Nn]º(.*?){}'.format(re_final_stj),
			r'\nAgRg no RECURSO ESPECIAL [Nn]º(.*?){}'.format(re_final_stj),
			r'\nRECURSO EM HABEAS CORPUS [Nn]º(.*?){}'.format(re_final_stj),
			r'\nHABEAS CORPUS [Nn]º(.*?){}'.format(re_final_stj)
			],
			['trf4',
			r'\nAPELAÇÃO CÍVEL Nº(.*?){}'.format(re_final_trf4),
			r'\nAPELAÇÃO.*?REMESSA NECESSÁRIA Nº(.*?){}'.format(re_final_trf4),
			r'\nAGRAVO DE INSTRUMENTO Nº(.*?){}'.format(re_final_trf4),
			r'\nEMBARGOS DE DECLARAÇÃO (.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO FISCAL Nº(.*?){}'.format(re_final_trf4),
			r'\nPROCEDIMENTO COMUM Nº(.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO DE SENTENÇA CONTRA FAZENDA (.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO DE TÍTULO (.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO H\s*?IPOTECÁR(.*?){}'.format(re_final_trf4),
			r'\nAÇÃO PENAL Nº(.*?){}'.format(re_final_trf4),
			r'\nMON\s*?ITÓR\s*?IA Nº(.*?){}'.format(re_final_trf4),
			r'\nREMESSA NECESSÁRIA CÍVEL Nº(.*?){}'.format(re_final_trf4),
			r'\nAPELAÇÃO.*?REEXAME NECESSÁRIO Nº(.*?){}'.format(re_final_trf4)
			],
			['trf3',
			r'\nAPELAÇÃO CÍVEL Nº(.*?){}'.format(re_final_trf4),
			r'\nAPELAÇÃO.*?REMESSA NECESSÁRIA Nº(.*?){}'.format(re_final_trf4),
			r'\nAGRAVO DE INSTRUMENTO Nº(.*?){}'.format(re_final_trf4),
			r'\nEMBARGOS DE DECLARAÇÃO(.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO FISCAL Nº(.*?){}'.format(re_final_trf4),
			r'\nPROCEDIMENTO COMUM Nº(.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO DE SENTENÇA CONTRA FAZENDA (.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO DE TÍTULO (.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO H\s*?IPOTECÁR(.*?){}'.format(re_final_trf4),
			r'\nAÇÃO PENAL Nº(.*?){}'.format(re_final_trf4),
			r'\nMON\s*?ITÓR\s*?IA Nº(.*?){}'.format(re_final_trf4),
			r'\nREMESSA NECESSÁRIA CÍVEL Nº(.*?){}'.format(re_final_trf4),
			r'\nAPELAÇÃO.*?REEXAME NECESSÁRIO Nº(.*?){}'.format(re_final_trf4)
			],
			['trf1',
			r'\nAPELAÇÃO CÍVEL Nº(.*?){}'.format(re_final_trf4),
			r'\nAPELAÇÃO.*?REMESSA NECESSÁRIA Nº(.*?){}'.format(re_final_trf4),
			r'\nAGRAVO DE INSTRUMENTO Nº(.*?){}'.format(re_final_trf4),
			r'\nEMBARGOS DE DECLARAÇÃO(.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO FISCAL Nº(.*?){}'.format(re_final_trf4),
			r'\nPROCEDIMENTO COMUM Nº(.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO DE SENTENÇA CONTRA FAZENDA (.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO DE TÍTULO (.*?){}'.format(re_final_trf4),
			r'\nEXECUÇÃO H\s*?IPOTECÁR(.*?){}'.format(re_final_trf4),
			r'\nAÇÃO PENAL Nº(.*?){}'.format(re_final_trf4),
			r'\nMON\s*?ITÓR\s*?IA Nº(.*?){}'.format(re_final_trf4),
			r'\nREMESSA NECESSÁRIA CÍVEL Nº(.*?){}'.format(re_final_trf4),
			r'\nAPELAÇÃO.*?REEXAME NECESSÁRIO Nº(.*?){}'.format(re_final_trf4)
			],
			['trt',
			r'\nProcesso Nº(.*?)(\nProcesso Nº|\nPROCESSO Nº|\nProcesso RO|\nPROCESSO N\.)',
			r'\nPROCESSO Nº(.*?)(\nProcesso Nº|\nPROCESSO Nº|\nProcesso RO|\nPROCESSO N\.)',
			r'\nProcesso RO(.*?)(\nProcesso Nº|\nPROCESSO Nº|\nProcesso RO|\nPROCESSO N\.)',
			r'\nPROCESSO N\.(.*?)(\nProcesso Nº|\nPROCESSO Nº|\nProcesso RO|\nPROCESSO N\.)',
			],
			['rs',
			r'\nEDITAL DE(.*?)(\nEDITAL DE|\n(?=\d{7})-|\n.*?CNJ.*?\d{5,7}-?)',
			r'\n(?=\d{7})-(.*?)(\nEDITAL DE|\n(?=\d{7})-|\n.*?CNJ.*?\d{5,7}-?)',
			r'\n.*?CNJ.*?\d{5,7}-?(.*?)(\nEDITAL DE|\n(?=\d{7})-|\n.*?CNJ.*?\d{5,7}-?)',
			],
			['rn',
			r'\nAPELAÇÃO(.*?){}'.format(re_final_rn),
			r'\nEMBARGOS DE(.*?){}'.format(re_final_rn),
			r'\nAGRAVO(.*?){}'.format(re_final_rn),
			r'\nCONFLITO NEGATIVO(.*?){}'.format(re_final_rn),
			r'\nMANDADO DE SEGUR(.*?){}'.format(re_final_rn),
			r'\nEXECUÇÃO N(.*?){}'.format(re_final_rn),
			r'\nEmbargos de(.*?){}'.format(re_final_rn),
			r'\nAgravo Interno(.*?){}'.format(re_final_rn),
			r'\nMandado de Segurança(.*?){}'.format(re_final_rn),
			r'\nApelação(.*?){}'.format(re_final_rn),
			r'\nExecução(.*?){}'.format(re_final_rn),
			r'\nAção Rescisória(.*?){}'.format(re_final_rn),
			r'\nADV:(.*?){}'.format(re_final_rn),
			r'\nAgravo de Instrumento(.*?){}'.format(re_final_rn)
			],
			['pb',
            r'\nAPELAÇÃO(.*?){}'.format(re_final_pb),
			r'\nEMBARGOS DE(.*?){}'.format(re_final_pb),
			r'\nAGRAVO(.*?){}'.format(re_final_pb),
			r'\nCONFLITO NEGATIVO(.*?){}'.format(re_final_pb),
			r'\nMANDADO DE SEGUR(.*?){}'.format(re_final_pb),
			r'\nRECURSO EM SENTIDO(.*?){}'.format(re_final_pb),
			r'\nREEXAME(.*?){}'.format(re_final_pb),
			r'\nRELATOR\(A\):(.*?){}'.format(re_final_pb),
			r'\nCOMARCA D(.*?){}'.format(re_final_pb),
			r'\nProcesso:(.*?){}'.format(re_final_pb),
			r'\nAgravo de Instrumento(.*?){}'.format(re_final_pb)
            ],
			['ms',
            r'\nProcesso (?=\d+)(.*?)\nProcesso (?=\d+)',
            ],
			['ac',
            r'Acórdão n(.*?){}'.format(re_final_pb),
			r'\n\d+\. Classe(.*?){}'.format(re_final_pb),
			r'\n\d+ - (?=\d{7})(.*?){}'.format(re_final_pb),
			r'\nADV:(.*?){}'.format(re_final_pb),
			r'\nProcesso: (.*?){}'.format(re_final_pb),
			r'\nProcesso(?=\d+)(.*?){}'.format(re_final_pb),
			r'\nAutos n\.º(.*?){}'.format(re_final_pb),
			r'IV - ADMINISTRATIVO(.*?){}'.format(re_final_pb)
			],
            ['al',
            r'\nADV:(.*?)\nADV:',
			],
			['ce',
            r'\n.*?DESPACHO DE RELATORES(.*?){}'.format(re_final_ce),
			r'\n.*?DEC\s*?ISÃO MONOCRÁT\s?ICA(.*?){}'.format(re_final_ce),
			r'\n.*?EMENTA E CONCLUSÃO(.*?){}'.format(re_final_ce),
			r'\n.*?PORTAR\s*?IA(.*?){}'.format(re_final_ce),
			r'\n.*?CONFL\s*?ITO DE JUR\s*?ISD(.*?){}'.format(re_final_ce),
			r'\n.*?EMBARGOS DE DECLARAÇÃO(.*?){}'.format(re_final_ce),
			r'\n.*?APELAÇÃO(.*?){}'.format(re_final_ce),
			r'\nD\s*?ISTR\s*?IBU\s*?IÇÃO(.*?){}'.format(re_final_ce),
			r'\n[Nn]º (?=\d\d\d\d+)(.*?){}'.format(re_final_ce)
			],
            ['to',
            r'\nAutos(.*?){}'.format(re_final_to),
			r'\nAUTOS N(.*?){}'.format(re_final_to),
			r'\nProcesso N(.*?){}'.format(re_final_to),
			r'\n\d+- Ação:(.*?){}'.format(re_final_to),
			r'\nAÇÃO(.*?){}'.format(re_final_to),
			r'\nEDITAL DE CITAÇÃO(.*?){}'.format(re_final_to),
			r'\nEDITAL DE INTIMAÇÃO(.*?){}'.format(re_final_to),
			r'\nPROCESSO N(.*?){}'.format(re_final_to)
			],
            ['pi',
            r'\nPROCESSOS N',
            r'\n\d{1,3}\.\d{1,3}\. HABEAS CORPUS(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. AGRAVO DE INSTRUMENTO N(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. REEXAME NECESSÁRIO N(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. APELAÇÃO(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. MANDADO DE SEGURANÇA(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. DESPACHO(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. EDITAL (.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. AVISO(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. ATO ORDINATÓRIO(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. SENTENÇA(.*?){}'.format(re_final_pi),
            r'\n\d{1,3}\.\d{1,3}\. AC.RDÃO(.*?){}'.format(re_final_pi)
            ],
			['ro',
            r'\nOrigem:(.*?){}'.format(re_final_ro),
			r'\nMandado de Segurança(.*?){}'.format(re_final_ro),
			r'\nNúmero do Processo(.*?){}'.format(re_final_ro),
			r'\nProcesso n(.*?){}'.format(re_final_ro),
			r'\nProc\.:(.*?){}'.format(re_final_ro),
			r'\nProcesso:(.*?){}'.format(re_final_ro)
			],
            ['ma',
            r'\nREQUERIMENTO DE(.*?){}'.format(re_final_ma),
            r'\nPETIÇÃO N(.*?){}'.format(re_final_ma),
            r'\nHABEAS CORPUS N(.*?){}'.format(re_final_ma),
            r'\nPORTARIA-TJ(.*?){}'.format(re_final_ma),
            r'\n\d{1,3}-PROCESSO(.*?){}'.format(re_final_ma),
            r'\nACÓRDÃO N(.*?){}'.format(re_final_ma),
            r'\nProcesso [Nn]º(.*?){}'.format(re_final_ma),
            r'\nProcesso:(.*?){}'.format(re_final_ma)
            ],
			['pa',
            r'\nPROCESSO:(.*?)\nPROCESSO:',
			],
            ['go',
            r'\n\s*?PROTOCOLO\s*?\:(.*?)(\n\s*?PROTOCOLO\s*?\:|\nNR\. PROTOCOLO|\n\s*?PROCESSO\s*?\:)',
            r'\nNR\. PROTOCOLO(.*?)(\n\s*?PROTOCOLO\s*?\:|\nNR\. PROTOCOLO|\n\s*?PROCESSO\s*?\:)',
            r'\n\s*?PROCESSO\s*?\:(.*?)(\n\s*?PROTOCOLO\s*?\:|\nNR\. PROTOCOLO|\n\s*?PROCESSO\s*?\:)'
			],
            ['ap',
            r'\nDISTRIBUIÇÃO(.*?)(\nDISTRIBUIÇÃO|\nN. do processo\:|\nVARA\:)',
			r'\nN. do processo\:(.*?)(\nDISTRIBUIÇÃO|\nN. do processo\:|\nVARA\:)',
			r'\nVARA\:(.*?)(\nDISTRIBUIÇÃO|\nN. do processo\:|\nVARA\:)'
			],
            ['rr',
            r'\n\d{3} - (?=\d{7})(.*?)\d{3} - (?=\d{7})',
			],
            ['am',
            r'\nPROCESSO DIGITAL: (.*?){}'.format(re_final_am),
            r'\nDe ordem d[oa](.*?){}'.format(re_final_am),
            r'\nDespacho proferido pel(.*?){}'.format(re_final_am),
            r'\n\d+ - Apelação n(.*?){}'.format(re_final_am),
            r'\nProcesso n\. (?=\d{7})(.*?){}'.format(re_final_am),
            r'\nProcesso :(?=\d{7})(.*?){}'.format(re_final_am),
            r'\n\d+\. PROCESSO:(?=\d{7})(.*?){}'.format(re_final_am),
            r'\nAutos n(?=\s*?\d{7})(.*?){}'.format(re_final_am),
            r'\n\s*?ADV:(.*?){}'.format(re_final_am)
            ],
            ['pr',
            r'\n\d{1,4} \. Processo[\:/](.*?)\n\d{1,4} \. Processo[\:/]'
            ],
            ['trf2',
            r'\nAPELAÇÃO CÍVEL Nº(.*?){}'.format(re_final_trf4),
            r'\nAPELAÇÃO.*?REMESSA NECESSÁRIA Nº(.*?){}'.format(re_final_trf4),
            r'\nAGRAVO DE INSTRUMENTO Nº(.*?){}'.format(re_final_trf4),
            r'\nEMBARGOS DE DECLARAÇÃO(.*?){}'.format(re_final_trf4),
            r'\nEXECUÇÃO FISCAL Nº(.*?){}'.format(re_final_trf4),
            r'\nPROCEDIMENTO COMUM Nº(.*?){}'.format(re_final_trf4),
            r'\nEXECUÇÃO DE SENTENÇA CONTRA FAZENDA (.*?){}'.format(re_final_trf4),
            r'\nEXECUÇÃO DE TÍTULO (.*?){}'.format(re_final_trf4),
            r'\nEXECUÇÃO H\s*?IPOTECÁR(.*?){}'.format(re_final_trf4),
            r'\nAÇÃO PENAL Nº(.*?){}'.format(re_final_trf4),
            r'\nMON\s*?ITÓR\s*?IA Nº(.*?){}'.format(re_final_trf4),
            r'\nREMESSA NECESSÁRIA CÍVEL Nº(.*?){}'.format(re_final_trf4),
            r'\nAPELAÇÃO.*?REEXAME NECESSÁRIO Nº(.*?){}'.format(re_final_trf4)
            ],
            ['sc',
            r'\n\s*ADV:(.*?){}'.format(re_final_sc),
            r'\nProcesso\s*(?=\d{7})(.*?){}'.format(re_final_sc),
            r'\n\d*\s*\.*\s*?Recurso (.*?){}'.format(re_final_sc),
            r'\n\d*\s*\.*\s*?Ag\s*ra\s*vo (.*?){}'.format(re_final_sc),
            r'\n\d*\s*\.*\s*?Embargo(.*?){}'.format(re_final_sc),
            r'\n\d*\s*\.*\s*?Apelação (.*?){}'.format(re_final_sc),
            r'\nRecurso (.*?){}'.format(re_final_sc),
            r'\n\s*N.\s*:(?=\d{4,7})(.*?){}'.format(re_final_sc)
			],
            ['df',
            r'\n\d{3}\. (?=\d{4})(.*?)\d{3}\. (?=\d{4})'
			],
            ['mg',
            r'\n\d{5} - (?=\d{7})(.*?)\n\d{5} - (?=\d{7})'
            ],
            ['rj',
            r'\nProc\.(.*?)\nProc\.'
            ],
            ['mt',
            r'\nProtocolo(.*?)(\nProtocolo|\nIntimação)',
            r'\nIntimação(.*?)(\nProtocolo|\nIntimação)'
            ],
            ['pe',
            r'\nProtocolo(.*?)(\nProtocolo|\nProcesso)',
            r'\nProcesso(.*?)(\nProtocolo|\nProcesso)'
            ],
            ['ba',
            r'DIREITO (?=\d{7}-\d{2}\.)(.*?)(DIREITO (?=\d{7}-\d{2}\.)|\nIntimação)',
            r'\nIntimação(.*?)(DIREITO (?=\d{7}-\d{2}\.)|\nIntimação)'
            ],
            ['trf5',
            r'\nPROTOCOLO N(.*?)(\nPROTOCOLO N|\n\d{4}\s*?\.\s*Processo)',
			r'\n\d{4}\s*?\.\s*Processo(.*?)(\nPROTOCOLO N|\n\d{4}\s*?\.\s*Processo)'
            ],
            ['se',
            r'\nNO\. PROCESSO(.*?)(\nNO\. PROCESSO|\nNO\. ACORDÃO|\nPROC\.\:)',
            r'\nNO\. ACORDÃO(.*?)(\nNO\. PROCESSO|\nNO\. ACORDÃO|\nPROC\.\:)',
            r'\nPROC\.\:(.*?)(\nNO\. PROCESSO|\nNO\. ACORDÃO|\nPROC\.\:)'
            ]
        ]

for a in arqs_i:
	for d in diarios:
		nome_arq = re.search(r""+d[0]+"\d+\.txt",a)
		if nome_arq != None:
			# definir forma de processamento dos diários para inserção na base após transformação do diário em txt
            break