-- MySQL Script generated by MySQL Workbench
-- Tue 07 Aug 2018 01:44:04 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema justica_estadual
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `justica_estadual` ;

-- -----------------------------------------------------
-- Schema justica_estadual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `justica_estadual` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema jurisprudencia_1_inst
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jurisprudencia_1_inst` ;

-- -----------------------------------------------------
-- Schema jurisprudencia_1_inst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jurisprudencia_1_inst` ;
-- -----------------------------------------------------
-- Schema jurisprudencia_2_inst
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jurisprudencia_2_inst` ;

-- -----------------------------------------------------
-- Schema jurisprudencia_2_inst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jurisprudencia_2_inst` DEFAULT CHARACTER SET utf8 ;
USE `justica_estadual` ;

-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_ac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_ac` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_ac` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_al`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_al` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_al` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_pa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_pa` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_pa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_ro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_ro` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_ro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_rr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_rr` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_rr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_rs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_rs` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_rs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_sc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_sc` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_sc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_se`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_se` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_se` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_sp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_sp` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_sp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_to`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_to` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_to` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_am`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_am` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_am` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_ba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_ba` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_ba` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_ce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_ce` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_ce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_df`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_df` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_df` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_es`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_es` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_es` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_go`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_go` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_go` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_ma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_ma` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_ma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_mg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_mg` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_mg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_ms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_ms` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_ms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_mt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_mt` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_mt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_pb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_pb` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_pb` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_pe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_pe` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_pe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_pi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_pi` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_pi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_pr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_pr` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_pr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_rj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_rj` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_rj` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `justica_estadual`.`jurisprudencia_rn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justica_estadual`.`jurisprudencia_rn` ;

CREATE TABLE IF NOT EXISTS `justica_estadual`.`jurisprudencia_rn` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ementas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `jurisprudencia_1_inst` ;

-- -----------------------------------------------------
-- Table `jurisprudencia_1_inst`.`assunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_1_inst`.`assunto` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_1_inst`.`assunto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_1_inst`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_1_inst`.`classe` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_1_inst`.`classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_1_inst`.`comarca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_1_inst`.`comarca` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_1_inst`.`comarca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_1_inst`.`julgador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_1_inst`.`julgador` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_1_inst`.`julgador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_1_inst`.`orgao_julgador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_1_inst`.`orgao_julgador` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_1_inst`.`orgao_julgador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_1_inst`.`tribunal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_1_inst`.`tribunal` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_1_inst`.`tribunal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_1_inst`.`jurisprudencia_1_inst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_1_inst`.`jurisprudencia_1_inst` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_1_inst`.`jurisprudencia_1_inst` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tribunal` INT NULL,
  `numero` VARCHAR(450) NULL,
  `id_assunto` INT NULL,
  `id_classe` INT NULL,
  `data_decisao` VARCHAR(45) NULL,
  `id_orgao_julgador` INT NULL,
  `id_julgador` INT NULL,
  `texto_decisao` LONGTEXT NULL,
  `relatorio` LONGTEXT NULL,
  `fundamentacao` LONGTEXT NULL,
  `dispositivo` LONGTEXT NULL,
  `polo_ativo` TEXT NULL,
  `polo_passivo` TEXT NULL,
  `id_comarca` INT NULL,
  `justica_gratuita` VARCHAR(45) NULL,
  `procedencia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_assunto_idx` (`id_assunto` ASC),
  INDEX `id_classe_idx` (`id_classe` ASC),
  INDEX `id_comarca_idx` (`id_comarca` ASC),
  INDEX `id_julgador_idx` (`id_julgador` ASC),
  INDEX `id_orgao_julgador_idx` (`id_orgao_julgador` ASC),
  INDEX `id_tribunal_idx` (`id_tribunal` ASC),
  CONSTRAINT `id_assunto`
    FOREIGN KEY (`id_assunto`)
    REFERENCES `jurisprudencia_1_inst`.`assunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_classe`
    FOREIGN KEY (`id_classe`)
    REFERENCES `jurisprudencia_1_inst`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_comarca`
    FOREIGN KEY (`id_comarca`)
    REFERENCES `jurisprudencia_1_inst`.`comarca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_julgador`
    FOREIGN KEY (`id_julgador`)
    REFERENCES `jurisprudencia_1_inst`.`julgador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_orgao_julgador`
    FOREIGN KEY (`id_orgao_julgador`)
    REFERENCES `jurisprudencia_1_inst`.`orgao_julgador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tribunal`
    FOREIGN KEY (`id_tribunal`)
    REFERENCES `jurisprudencia_1_inst`.`tribunal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `jurisprudencia_2_inst` ;

-- -----------------------------------------------------
-- Table `jurisprudencia_2_inst`.`assunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_2_inst`.`assunto` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_2_inst`.`assunto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_2_inst`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_2_inst`.`classe` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_2_inst`.`classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_2_inst`.`origem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_2_inst`.`origem` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_2_inst`.`origem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_2_inst`.`julgador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_2_inst`.`julgador` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_2_inst`.`julgador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_2_inst`.`orgao_julgador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_2_inst`.`orgao_julgador` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_2_inst`.`orgao_julgador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_2_inst`.`tribunal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_2_inst`.`tribunal` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_2_inst`.`tribunal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(450) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudencia_2_inst`.`jurisprudencia_2_inst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudencia_2_inst`.`jurisprudencia_2_inst` ;

CREATE TABLE IF NOT EXISTS `jurisprudencia_2_inst`.`jurisprudencia_2_inst` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tribunal` INT NULL,
  `numero` VARCHAR(450) NULL,
  `id_assunto` INT NULL,
  `id_classe` INT NULL,
  `data_decisao` VARCHAR(45) NULL,
  `id_orgao_julgador` INT NULL,
  `id_julgador` INT NULL,
  `texto_decisao` LONGTEXT NULL,
  `relatorio` LONGTEXT NULL,
  `fundamentacao` LONGTEXT NULL,
  `dispositivo` LONGTEXT NULL,
  `polo_ativo` TEXT NULL,
  `polo_passivo` TEXT NULL,
  `id_origem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_assunto_idx` (`id_assunto` ASC),
  INDEX `id_classe_idx` (`id_classe` ASC),
  INDEX `id_origem_idx` (`id_origem` ASC),
  INDEX `id_julgador_idx` (`id_julgador` ASC),
  INDEX `id_orgao_julgador_idx` (`id_orgao_julgador` ASC),
  INDEX `id_tribunal_idx` (`id_tribunal` ASC),
  CONSTRAINT `id_assunto`
    FOREIGN KEY (`id_assunto`)
    REFERENCES `jurisprudencia_2_inst`.`assunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_classe`
    FOREIGN KEY (`id_classe`)
    REFERENCES `jurisprudencia_2_inst`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_origem`
    FOREIGN KEY (`id_origem`)
    REFERENCES `jurisprudencia_2_inst`.`origem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_julgador`
    FOREIGN KEY (`id_julgador`)
    REFERENCES `jurisprudencia_2_inst`.`julgador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_orgao_julgador`
    FOREIGN KEY (`id_orgao_julgador`)
    REFERENCES `jurisprudencia_2_inst`.`orgao_julgador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tribunal`
    FOREIGN KEY (`id_tribunal`)
    REFERENCES `jurisprudencia_2_inst`.`tribunal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
