-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 13:22:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jurisprudenciaDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jurisprudenciaDB` ;

-- -----------------------------------------------------
-- Schema jurisprudenciaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jurisprudenciaDB` DEFAULT CHARACTER SET utf8 ;
USE `jurisprudenciaDB` ;

-- -----------------------------------------------------
-- Table `jurisprudenciaDB`.`publicacoes_brutas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudenciaDB`.`publicacoes_brutas` ;

CREATE TABLE IF NOT EXISTS `jurisprudenciaDB`.`publicacoes_brutas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_publicacao` VARCHAR(45) NULL,
  `texto_publicacao` LONGTEXT NULL,
  `data` VARCHAR(45) NULL,
  `tribunal_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_tribunal_idx` (`tribunal_id` ASC) VISIBLE,
  CONSTRAINT `id_tribunal`
    FOREIGN KEY (`tribunal_id`)
    REFERENCES `jurisprudenciaDB`.`tribunal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudenciaDB`.`tribunal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudenciaDB`.`tribunal` ;

CREATE TABLE IF NOT EXISTS `jurisprudenciaDB`.`tribunal` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudenciaDB`.`variaveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudenciaDB`.`variaveis` ;

CREATE TABLE IF NOT EXISTS `jurisprudenciaDB`.`variaveis` (
  `id` INT NOT NULL,
  `nome` TEXT NULL,
  `json_regras` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurisprudenciaDB`.`variaveis_publicacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jurisprudenciaDB`.`variaveis_publicacoes` ;

CREATE TABLE IF NOT EXISTS `jurisprudenciaDB`.`variaveis_publicacoes` (
  `id` INT NOT NULL,
  `variavel_id` INT NULL,
  `publicacao_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_variavel_idx` (`variavel_id` ASC) VISIBLE,
  INDEX `id_publicacao_idx` (`publicacao_id` ASC) VISIBLE,
  CONSTRAINT `id_variavel`
    FOREIGN KEY (`variavel_id`)
    REFERENCES `jurisprudenciaDB`.`variaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_publicacao`
    FOREIGN KEY (`publicacao_id`)
    REFERENCES `jurisprudenciaDB`.`publicacoes_brutas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
